# Authentic Catppuccin Latte Alacritty Configuration
# ~/.config/alacritty/alacritty.toml
# Based on the official Catppuccin Latte theme
[window]
opacity = 1
padding = { x = 8, y = 8 }

[font]
size = 13.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[mouse.bindings]]
mouse = "Left"
mods = "Control"
command = { program = "open", args = [] }

[general]
import = ["~/.config/alacritty/themes/themes/kanagawa_wave.toml"]


[env]
TERM = "xterm-256color"
